/-
Test: a macro that generates declarations, consumed by downstream code.
Tests whether the TFB skeleton correctly handles macro-generated syntax.
-/
import Lean

open Lean Elab Command in
-- A macro that generates a structure
macro "gen_point_struct" name:ident : command =>
  `(structure $name where
      x : Nat
      y : Nat)

-- Use the macro to generate a structure
gen_point_struct MyPoint

-- Declarations that use the macro-generated structure
def MyPoint.origin : MyPoint := ⟨0, 0⟩

theorem MyPoint.origin_x : MyPoint.origin.x = 0 := rfl

-- A simp lemma
@[simp] theorem MyPoint.x_origin : (MyPoint.origin).x = 0 := rfl

-- Downstream theorem using the simp lemma
theorem MyPoint.test : (MyPoint.origin).x = 0 := by simp

-- A class generated by deriving
deriving instance BEq for MyPoint

-- A def that uses the derived instance
def MyPoint.eq_origin (p : MyPoint) : Bool := p == MyPoint.origin
